export const getProducts = async () => {
  // Simulamos un fetch a una API
  return [
    {
      id: 1,
      name: 'Helecho',
      description: 'Planta de interior resistente',
      price: 15000,
      image: 'https://aiph.org/wp-content/uploads/2021/08/Nevada-fern.jpg',
      category: 'interior',
    },
    {
      id: 2,
      name: 'Cactus pequeño',
      description: 'Ideal para escritorios',
      price: 8000,
      image: 'https://th.bing.com/th/id/OIP.x7vauU2teoJnOmsVJM3STQHaE8?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'suculentas',
    },
    {
      id: 3,
      name: 'Palma Areca',
      description: 'Perfecta para interiores amplios',
      price: 25000,
      image: 'https://http2.mlstatic.com/palmera-areca-planta-de-interior-15-litros-D_NQ_NP_881254-MLA27379178149_052018-F.jpg',
      category: 'interior',
    },
    {
      id: 4,
      name: 'Rosa roja',
      description: 'Flor de jardín muy apreciada',
      price: 12000,
      image: 'https://th.bing.com/th/id/OIP.zBddEnGm1q1p4pfx8eP8vQHaJ4?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'exterior',
    },
    {
      id: 5,
      name: 'Lavanda',
      description: 'Aromática ideal para jardines',
      price: 10000,
      image: 'https://www.cuerpomente.com/medio/2020/07/29/lavanda-cuadrada_26eb3145_1200x1200.jpg',
      category: 'exterior',
    },
    {
      id: 6,
      name: 'Semillas de girasol',
      description: 'Listas para germinar',
      price: 3000,
      image: 'https://mejorconsalud.as.com/wp-content/uploads/2022/10/semillas-girasol.jpg',
      category: 'semillas',
    },
    {
      id: 7,
      name: 'Suculenta Jade',
      description: 'Resistente y fácil de cuidar',
      price: 9500,
      image: 'https://cdn.awsli.com.br/2500x2500/2429/2429322/produto/161323439/9ef16c55e4.jpg',
      category: 'suculentas',
    },
    {
      id: 8,
      name: 'Bambú de la suerte',
      description: 'Atrae buenas energías',
      price: 14000,
      image: 'https://th.bing.com/th/id/OIP.qsri0UYqFgNG34-rbe8xyQHaGm?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'interior',
    },
    {
      id: 9,
      name: 'Orquídea blanca',
      description: 'Elegante y delicada',
      price: 22000,
      image: 'https://th.bing.com/th/id/OIP.LAUbJUyq41z4qZxlp5IaWwHaHa?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'interior',
    },
    {
      id: 10,
      name: 'Aloe Vera',
      description: 'Planta medicinal con muchos usos',
      price: 12000,
      image: 'https://m.media-amazon.com/images/I/81XWpVvk5AL._AC_UF1000,1000_QL80_.jpg',
      category: 'suculentas',
    },
    {
      id: 11,
      name: 'Semillas de albahaca',
      description: 'Perfectas para cocina casera',
      price: 2500,
      image: 'https://th.bing.com/th/id/OIP.94zhPoGVwuecOKLhVq9yawHaFS?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'semillas',
    },
    {
      id: 12,
      name: 'Tulipán amarillo',
      description: 'Flor brillante y alegre',
      price: 11000,
      image: 'https://th.bing.com/th/id/OIP.s90f7VzMRwoUxVwjPaCDSgHaE8?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'exterior',
    },
    {
      id: 13,
      name: 'Helecho plumoso',
      description: 'Ideal para sombra y humedad',
      price: 13500,
      image: 'https://th.bing.com/th/id/OIP.DNct1sd1O_nqTL6oJtZP8wHaHa?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'interior',
    },
    {
      id: 14,
      name: 'Semillas de tomate cherry',
      description: 'Cultivo en casa fácil',
      price: 4000,
      image: 'https://http2.mlstatic.com/D_NQ_NP_978172-MCO43558084032_092020-F.jpg',
      category: 'semillas',
    },
    {
      id: 15,
      name: 'Cactus redondo',
      description: 'Decorativo y compacto',
      price: 7000,
      image: 'https://th.bing.com/th/id/OIP.TxO5qL2NnGOVGJuIiDS4_wHaG8?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'suculentas',
    },
    {
      id: 16,
      name: 'Petunia morada',
      description: 'Flor de estación muy vistosa',
      price: 9000,
      image: 'https://i.pinimg.com/originals/82/92/23/829223f24ca98fc8c7ddc4bcb81b95f4.jpg',
      category: 'exterior',
    },
    {
      id: 17,
      name: 'Ficus Lyrata',
      description: 'Popular en decoración de interiores',
      price: 27000,
      image: '',
      category: 'interior',
    },
    {
      id: 18,
      name: 'Semillas de cilantro',
      description: 'Hierba aromática esencial',
      price: 2000,
      image: 'https://th.bing.com/th/id/R.dbd1fabfa57f25815add26178f997e0b?rik=2e73Omk%2bQTbM%2bg&pid=ImgRaw&r=0',
      category: 'semillas',
    },
    {
      id: 19,
      name: 'Rosal miniatura',
      description: 'Floración continua todo el año',
      price: 16000,
      image: 'https://th.bing.com/th/id/OIP.4Rb4AItrWalONKEDf3iWiwAAAA?cb=iwp2&rs=1&pid=ImgDetMain',
      category: 'exterior',
    },
    {
      id: 20,
      name: 'Echeveria Elegans',
      description: 'Suculenta con forma de flor',
      price: 10000,
      image: 'https://i.redd.it/dqalf0pc3mk11.jpg',
      category: 'suculentas',
    },
  ];
};
